# Generated by Django 2.1.2 on 2018-10-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorafi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gorafi',
            name='onglet_to_display',
            field=models.IntegerField(default=1),
        ),
    ]
