version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: dashboard
      POSTGRES_USER: dashboard
      POSTGRES_DB: dashboard

  web:
    build: .
    environment:
      DB_USER: dashboard
      DB_PASSWORD: dashboard
      DB_NAME: dashboard
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db