version: "3"
services:
  server:
    container_name: server
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
    command: '--smallfiles --logpath=/dev/null'
    environment:
      MONGODB_DATABASE: "user"

volumes:
  mongodata: