# Generated by Django 2.1.2 on 2018-10-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube_subs',
            name='channel',
            field=models.CharField(help_text='Channel username, example : pewdiepie', max_length=30),
        ),
    ]
