# Generated by Django 2.1.2 on 2018-10-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_service', '0002_auto_20181016_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube_subs',
            name='channel',
            field=models.CharField(max_length=30),
        ),
    ]
