# Generated by Django 2.1.2 on 2018-10-16 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtube_service', '0002_auto_20181016_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube_views',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Videos view',
            },
        ),
        migrations.AlterField(
            model_name='youtube_subs',
            name='channel',
            field=models.CharField(max_length=30),
        ),
    ]
