# Generated by Django 2.1.2 on 2018-10-19 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_service', '0003_auto_20181016_1427'),
        ('youtube_service', '0003_auto_20181016_1039'),
    ]

    operations = [
    ]
