# Generated by Django 2.1.2 on 2018-10-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_service', '0005_youtube_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube_popular',
            name='nb',
            field=models.IntegerField(default=5),
        ),
    ]
