# Generated by Django 2.1.2 on 2018-10-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citytemperature',
            options={'verbose_name_plural': 'Cities temperature'},
        ),
        migrations.AlterModelOptions(
            name='cityweather',
            options={'verbose_name_plural': 'Cities weather'},
        ),
        migrations.AlterField(
            model_name='citytemperature',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='cityweather',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
