# Generated by Django 2.1.2 on 2018-10-09 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_service', '0002_auto_20181008_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citytemperature',
            name='user',
        ),
        migrations.DeleteModel(
            name='CityTemperature',
        ),
    ]
